version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rental_management_db
    restart: always
    environment:
      POSTGRES_USER: rental_user
      POSTGRES_PASSWORD: rental_password
      POSTGRES_DB: rental_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rental_network

volumes:
  postgres_data:

networks:
  rental_network:
    driver: bridge
